[[language]]
name = "svelte"
indent = { tab-width = 4, unit = "\t" }
auto-format = true
roots = ["svelte.config.js"]
# formatter: the svelteserver LSP automatically uses prettier (I think)
language-servers = ["svelteserver", "tailwindcss-ls"]

[[language]]
name = "typescript"
roots = ["deno.json", "deno.jsonc", "package.json"]
auto-format = true
language-servers = ["deno-lsp"]

[[language]]
name = "javascript"
roots = ["deno.json", "deno.jsonc", "package.json"]
auto-format = true
language-servers = ["deno-lsp"]

[[language]]
name = "graphql"
comment-token = "#"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "toml"
auto-format = true
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "json"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "html"
scope = "text.html.basic"
injection-regex = "html"
file-types = [
	"html",
	"htm",
	"tmpl",   # Temp for go html tmpl files till I fix my LSP
	"shtml",
	"xhtml",
	"xht",
	"jsp",
	"asp",
	"aspx",
	"jshtm",
	"volt",
	"rhtml",
	"cshtml",
]
block-comment-tokens = { start = "<!--", end = "-->" }
language-servers = ["superhtml", "tailwindcss-ls", "emmet-lsp"]
auto-format = true

[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

[language-server.emmet-lsp]
command = "emmet-ls"
args = ["--stdio"]

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]
config.deno.enable = true
